[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pmvs"
version = "0.1.0"
description = "Poor Mans Vector Store"
authors = [
    { name="Andrew Boney", email="andrew.boney@hotmail.co.uk" }
]